parameters:
#    vince_t_base.example.class: VinceT\BaseBundle\Example

services:
#    vince_t_base.example:
#        class: %vince_t_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
